- name: Add ssh key for muser
  authorized_key:
    user: muser
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7L7Z/s7Yn7Adk9c9FiQQU77XxzF3BwJlWWxADxL7m1 ansible"

- name: generate sshd_config file form template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
